#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-chains-info.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

const
  _libcrash =
  require(
    "crash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _process_exit */
const
_process_exit =
  _libcrash._process_exit;


const
  _libevm_module =
    require(
      "libevm");
/* global
     _libevm_global_variables */
const
  _libevm_global_variables =
    _libevm_module._libevm_global_variables;
/* global
     _wallet_overrides_set */
const
  _wallet_overrides_set =
    _libevm_module._wallet_overrides_set;
const
  _libevm_chains_info_module =
    require(
      "libevm-chains-info");
/* global
     _evm_chains_db_path_get */
const
  _evm_chains_db_path_get =
    _libevm_chains_info_module._evm_chains_db_path_get;
/* global
     _evm_chains_info_get */
const
  _evm_chain_info_get =
    _libevm_chains_info_module._evm_chain_info_get;
/* global
     _rpc_backends_get */
const
  _rpc_backend_get =
    _libevm_chains_info_module._rpc_backend_get;
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _libevm_chains_info_module._evm_chains_info;
/* global
     _db_paths_auto_detect */
const
  _db_paths_auto_detect =
    _libevm_chains_info_module._db_paths_auto_detect;
/* global
     _input_type_auto_detect */
const
  _input_type_auto_detect =
    _libevm_chains_info_module._input_type_auto_detect;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "evm-contract-call.js";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       runtime_environment:
         writable */
  runtime_environment =
    "";
  /* global
       call_date:
         writable */
  call_date =
    "";
  /* global
       call_type:
         writable */
  call_type =
    "";
  /* global
       index_retrieve:
         writable */
  index_retrieve =
    "";
  /* global
       contract_address:
         writable */
  contract_address =
    "";
  /* global
       contract_bytecode:
         writable */
  contract_bytecode =
    "";
  /* global
       contract_compiler_output:
         writable */
  contract_compiler_output =
    "";
  /* global
       contract_abi:
         writable */
  contract_abi =
    "";
  /* global
       contract_method:
         writable */
  contract_method =
    "";
  /* global
       method_args:
         writable */
  method_args =
    [];
  /* global
       price_gas:
         writable */
  price_gas =
    "";
  /* global
       measure_unit:
         writable */
  measure_unit =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
  /* global
       verbose:
         writable */
  verbose =
    "";
}

function 
  _overrides_set() {
  if ( call_date == "" ) {
    call_date =
      _get_date_human();
  }
  if ( wallet_name == "" ) {
    wallet_name =
      "default";
  }
  if ( index_retrieve == "" ) {
    index_retrieve =
      "n";
  }
  if ( retries_max == "" ) {
    retries_max =
      "300";
  }
  if ( target_network == "" ) {
    // to be auto-detected
    target_network =
      "1";
  }
  if ( rpc_selection == "" ) {
    rpc_selection =
      "kirsh";
  }
  if ( call_type == "" ) {
    call_type =
      "static";
  }
  _call_auth_auto_detect();
  if ( call_timeout == "" ) {
    call_timeout =
      "300000";
  }
  if ( measure_unit == "" ) {
    measure_unit =
      "ether";
  }
  if ( msg_value == "" ) {
    msg_value =
      "0";
  }
  // _api_key_auto_detect();
  if ( contract_address != "" ) {
    if ( contract_abi == "" ) {
      contract_abi =
        _default_artifact_path_get();
      _artifact_local_auto_detect(
        "bytecode");
      _artifact_local_auto_detect(
        "compiler_output");
      if ( contract_abi == "" ||
           _default_artifact_path_get(
	     "abi") == contract_abi ) {
        _contract_abi_auto_detect();
      }
    }
  }
  _wallet_overrides_set(
    "evm-wallet",
    wallet_name,
    call_auth);
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `${app_name} configuration:`,
      `                Call date:   ${call_date}`,
      `      Runtime environment:   ${runtime_environment}`,
      `           Target command:   ${target_command}`,
      `               Input type:   ${input_type}`,
      `              Output type:   ${output_type}`,
      `           Retrieval mode:   ${retrieval_mode}`,
      `      User-level database:   ${user_level}`,
      `                  API key:   ${api_key}`,
      `     RPC selection method:   ${selection_method}`,
      `             All networks:   ${networks_all}`,
      `             Target chain:   ${target_chain}`,
      `           Database paths:   ${db_paths}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "Returns info about EVM blockchains.",
      "",
      "Usage:",
      "",
      "  evm-chains-info.js",
      "    [options]",
      "    <target-chain>",
      "",
      "  options:",
      "",
      "     -C --command                    Target command. Can be 'get' or 'set'.",
      `       <target-command>              Default: '${target_command}`,
      "",
      "     -i --input-type                 Input type. It can be 'id' or 'name'.",
      `       <input-type>                  Default: '${input_type}'`,
      "",
      "     -o --output-type                Output type. It can be 'id', 'name',",
      "       <output-type>                 'rpc', 'explorers'.",
      `                                     Default: '${output_type}'`,
      "",
      "     -m --retrieval-mode             It can be 'offline'.",
      `       <retrieval-mode>              Default: '${retrieval_mode}'`,
      "",
      "     -u --user-level                 It can be 'y' or 'n'.",
      `       <user-level>                  Default: '${user_level}'`,
      "",
      "     -d --db-path                    Path of the chains' info json file",
      "       <db-path>                     to be used for 'offline' retrieval.",
      `                                     Default: '${db_paths}'`,
      "",
      "     -s --selection-method           When output type is 'rpc',",
      "       <selection-method>            selection criterion to use when",
      "                                     more than one is available.",
      "                                     It can be 'kirsh', 'random' or 'all'.",
      `                                     Default: '${selection_method}'`,
      "",
      "     -k                              If selected, when output type is 'rpc',",
      "                                     includes the ones requiring an API key.",
      `                                     Default: '${api_key}'`,
      "     -a --all                        Whether to show results for all networks.",
      `                                     Default: '${networks_all}'`,
      "",
      "     -h --help                       This message.",
      "     -v --verbose                    Enable verbose output."
    ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _process_exit(
    _exit_code);
}

function 
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "h",
        "help",
        "v",
        "verbose"
      ]
    };
  const
    _argv =
      _argv_get(
        _argv_args);
  const
    _options =
      _argv[
        "_"];
  quiet = 
    "y";
  runtime_environment =
    "node";
  if ( _argv["h"] == true ) {
    _help_display =
      true;
  }
  if ( _argv["help"] == true ) {
    _help_display =
      true;
  }
  if ( ( _options.indexOf(
           "--help") > -1 ||
         _options.indexOf(
           "-h") > -1) ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    quiet =
      "n";
    _overrides_set();
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Contract address argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  contract_address =
    _argv[
      "_"][
        0];
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 2 ) {
    _msg =
      "Contract method argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  contract_method =
    _argv[
      "_"][
        0];
  const
    method_args =
      _out.slice(
        2,
        _argv[
          "_"].length - 2);
  if ( "t" in _argv ) {
    call_type =
      _argv[
        "t"];
  }
  if ( "call-type" in _argv ) {
    call_type =
      _argv[
        "call-type"];
  }
  if ( "T" in _argv ) {
    call_timeout =
      _argv[
        "t"];
  }
  if ( "call-timeout" in _argv ) {
    call_timeout =
      _argv[
        "call-timeout"];
  }
  if ( "I" in _argv ) {
    index_retrieve =
      _argv[
        "I"];
  }
  if ( "index_retrieve" in _argv ) {
    index_retrieve =
      _argv[
        "index-retrieve"];
  }
  if ( "P" in _argv ) {
    price_gas =
      _argv[
        "P"];
  }
  if ( "price-gas" in _argv ) {
    price_gas =
      _argv[
        "price-gas"];
  }
  if ( "u" in _argv ) {
    measure_unit =
      _argv[
        "u"];
  }
  if ( "measure-unit" in _argv ) {
    measure_unit =
      _argv[
        "measure-unit"];
  }
  if ( "V" in _argv ) {
    msg_value =
      _argv[
        "V"];
  }
  if ( "msg-value" in _argv ) {
    msg_value =
      _argv[
        "msg-value"];
  }
  if ( "r" in _argv ) {
    retries_max =
      _argv[
        "r"];
  }
  if ( "retries-max" in _argv ) {
    retries_max =
      _argv[
        "retries-max"];
  }
  if ( "S" in _argv ) {
    rpc_selection =
      _argv[
        "S"];
  }
  if ( "rpc-selection" in _argv ) {
    rpc_selection =
      _argv[
        "rpc-selection"];
  }
  if ( "A" in _argv ) {
    contract_abi =
      _argv[
        "A"];
  }
  if ( "contract-abi" in _argv ) {
    contract_abi =
      _argv[
        "contract-abi"];
  }
  if ( "C" in _argv ) {
    contract_compiler_output =
      _argv[
        "C"];
  }
  if ( "contract-compiler-output" in _argv ) {
    contract_compiler_output =
      _argv[
        "contract-compiler-output"];
  }
  if ( "a" in _argv ) {
    call_auth =
      "y";
  }
  if ( "call-auth" in _argv ) {
    call_auth =
      "y";
  }
  if ( "n" in _argv ) {
    target_networks.push(
      _argv[
        "n"]);
  }
  if ( "network" in _argv ) {
    target_networks.push(
      _argv[
        "network"]);
  }
  if ( "v" in _argv ) {
    verbose =
      true;
  }
  if ( "verbose" in _argv ) {
    verbose =
      true;
  }
  if ( verbose ) {
    quiet =
      "n";
  }
}

function
  _url_parse() {
  runtime_environment =
    "browser";
  target_chain =
    _argv_url_get(
      "chain")[
        0];
  target_command =
    _argv_url_get(
      "command")[
        0];
  input_type =
    _argv_url_get(
      "input_type")[
        0];
  output_type =
    _argv_url_get(
      "output_type")[
        0];
  input_type =
    _argv_url_get(
      "input_type")[
        0];
  retrieval_mode =
    _argv_url_get(
      "retrieval_mode")[
        0];
  user_level =
    _argv_url_get(
      "user_level")[
        0];
  db_paths.push(
    _argv_url_get(
      "db_path")[
        0]);
  selection_method =
    _argv_url_get(
      "selection_method")[
        0];
  api_key =
    _argv_url_get(
      "api_key")[
        0];
  networks_all =
    _argv_url_get(
      "networks_all")[
        0];
  quiet =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

function
  _evm_contract_call_cmdline(
    _app_opts) {
  let
    _result;
  const
    _results =
      _evm_contract_call.apply(
        null,
        app_opts);
  for ( _result of _results ) {
    console.log(
      _result);
  }
}

_global_variables();
_libevm_global_variables();
if ( _cmdline_check(
       "evm-contract-call.js") == true ||
     _cmdline_check(
            "evm-contract-call") == true ) {
  _cmdline_parse();
}
else{
  _url_parse();
}
_overrides_set();
_config_show();
app_opts = [
  target_command,
  input_type,
  output_type,
  retrieval_mode,
  selection_method,
  api_key,
  networks_all,
  target_chain,
  db_paths
];
_evm_contract_call_cmdline(
  app_opts);
