#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-chains-info
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
/* eslint-disable
     no-useless-assignment */

/* global 
     db_paths */
/* global
     input_type:
       writable */
/* global
     user_level */
/* global
     target_chain */

const
  _libcrash_module =
    require(
      "crash-js");
/* global
     _homedir_get */
/* eslint-disable-next-line
     no-global-assign */
_homedir_get =
  _libcrash_module._homedir_get;
/* global
     _file_exists */
/* eslint-disable-next-line
     no-global-assign */
_file_exists =
  _libcrash_module._file_exists;
/* global
     _json_read */
/* eslint-disable-next-line
     no-global-assign */
_json_read =
  _libcrash_module._json_read;
/* global
     _lib_get */
/* eslint-disable-next-line
     no-global-assign */
_lib_get =
  _libcrash_module._lib_get;
/* global
     _msg_info */
/* eslint-disable-next-line
     no-global-assign */
_msg_info =
  _libcrash_module._msg_info;
/* global
     _msg_error */
/* eslint-disable-next-line
     no-global-assign */
_msg_error =
  _libcrash_module._msg_error;
/* global
     _path_join */
/* eslint-disable-next-line
     no-global-assign */
_path_join =
  _libcrash_module._path_join;
/* global
     _range */
/* eslint-disable-next-line
     no-global-assign */
_range =
  _libcrash_module._range;

const
  _ethereum_data_module =
    require(
      "ethereum-data");
/* global
     _data_get */
const
  _data_get =
    _ethereum_data_module._data_get;

function
  _target_networks_auto_detect() {
  // TODO:
  //   _evm_wallet_module.balance-discovery
  if ( target_networks == "" ||
       target_networks == [] ) {
    // to be auto-detected
    target_networks = [
      "1"
    ];
  }
  if ( target_network == "" ) {
    // to be auto-detected
    target_network =
      "1";
  }
}


function
  _evm_chains_db_path_get(
    _user,
    _chain_id,
    _format) {
  let
    _db_name,
    _db_path,
    _msg;
  if ( typeof(
         _user) == "undefined" ||
       _user == "" ) {
    _user =
      "n";
  }
  if ( typeof(
         _chain_id) == "undefined" ||
       _chain_id == "" ) {
    _chain_id =
      "";
  }
  if ( typeof(
         _format) == "undefined" ||
      _format == "" ) {
    if ( _chain_id != "" ) {
      _format =
        "split";
    }
    else if ( _chain_id == "" ) {
      _format =
        "unified";
    }
  }
  _msg =
    `Getting path for chain ` +
    `with chain id '${_chain_id}' ` +
    `with privilege user set to ` +
    `'${_user}' in format '${_format}'.`;
  _msg_info(
    _msg);
  if ( _format == "unified" ) {
    _db_name =
      "chains.json";
  }
  else if ( _format == "split" ) {
    _db_name =
      `${_chain_id}.json`;
  }
  if ( _user == "y" ) {
    const
      _home_dir =
        _homedir_get();
    _msg =
      `Home directory: '${_home_dir}'`;
    _msg_info(
      _msg);
    _db_path =
      _path_join(
        [ _home_dir,
          ".config",
          "evm-chains",
          _db_name ]);
    const
      _db_exists =
        _file_exists(
          _db_path);
    if ( _db_exists == true ) {
      _msg =
        `Found database '${_db_path}'.`;
      _msg_info(
        _msg);
    }
    else if ( _db_exists == false ) {
      _msg =
        `Database '${_db_path}' ` +
        "not found";
      _msg_info(
        _msg);
      // _user =
      //   "n";
    }
    else {
      _msg =
        "wat";
      _msg_error(
        _msg);
    }
  }
  else if ( _user == "n" ) {
    const
      _lib =
        _lib_get();
    _db_path =
      _path_join(
        [ _lib,
          "evm-chains",
          _db_name ]);
  }
  else {
    _msg =
      "Input variable '_user' must be a boolean. " +
      `_user value is '${_user}'.`;
    _msg_error(
      _msg,
      0);
  }
  return _db_path;
}

function
  _evm_chain_info_get(
    _chain_id,
    _db_path,
    _user_level,
    _format,
    _db_types) {
  let
    _chain_info,
    _data,
    _msg;
  if ( typeof(
         _user_level) == "undefined" ) {
    _user_level =
      false;
  }
  if ( typeof(
         _format) == "undefined" ) {
    _format =
      "split";
  }
  if ( typeof(
         _db_path) == "undefined" ) {
    _db_path =
      _evm_chains_db_path_get(
        _user_level,
        _chain_id,
        _format);
  }
  const
    _db_exists =
      _file_exists(
        _db_path);
  if ( _db_exists == false ) {
    if ( typeof window === 'undefined' &&
         ( typeof global !== 'undefined' && global.global === global ) &&
         typeof __webpack_require__ !== 'function' ) {
      _data =
        _data_get(
          _chain_id);
      _msg =
        `Displaying data for ` +
        `chain '${_chain_id}' `+
        `of type '${_db_types}'.`;
      _msg_info(
        _msg);
      console.log(
        _data);
    }
    // _msg_error(
    //   "Database file does not exists.",
    //   1);
  }
  const 
    _db =
      _json_read(
        _db_path);
    // _data =
    //   _data_get(
    //     _chain_id);
    _msg =
      `Displaying data for ` +
      `chain '${_chain_id}' `+
      `of type '${_db_types}'.`;
    _msg_info(
      _msg);
    // console.log(
    //   _db);
  for ( _chain_info of _db) {
    if ( _chain_info["chainId"] == _chain_id ) {
      return _chain_info;
    }
  }
  _msg_error(
    `Network '${_chain_id}' not found.`,
    1);
}

function
  _evm_contract_call(
    _call_type,
    _call_timeout,
    _wallet_name,
    _wallet_path,
    _wallet_password,
    _wallet_seed,
    _api_key,
    _msg_value,
    _price_gas,
    _measure_unit,
    _retries_max,
    _target_networks,
    _rpc_selection,
    _contract_address,
    _contract_abi,
    _contract_bytecode,
    _contract_compiler_output,
    _contract_method,
    _method_args) {
  let
    _explorer,
    _result,
    _rpc;
  if ( _call_type == "static" ) {
    const
      _infos =
        [];
  else if ( _call_type == "dynamic" ) {
    true;
  }
  else {
    const
      _msg =
        `Unknown call type ` +
        `'${_call_type}'.`;
    _msg_error(
      _msg,
      1);
  }
}

module.exports = {
  _evm_contract_call:
    _evm_contract_call,
  _target_networks_auto_detect:
    _target_networks_auto_detect
};
